In [1]:
import torch
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Set the path to the directory where the files are located
save_path1 = '../CircuitNet-N28/training_set/IR_drop/feature/'
save_path2 = '../CircuitNet-N28/training_set/IR_drop/feature2/'
result_dict = {}

In [2]:
# all tensor sizes are [256, 256, 24]
c = 0
# Loop through all files in the directory
maxr = -99
minr = 99
for filename in os.listdir(save_path1):
    # Check if the file has the expected format
    # print(filename, tensor.shape)
    if filename.endswith('.npy'):
        data = np.load(os.path.join(save_path1, filename))
        tensor = torch.from_numpy(data)
        c+=1
        # if(c==20): break
        print(filename, tensor.shape)

        # # 均值,累加,最小,最大,累积
        # print(tensor.mean(), tensor.sum(), tensor.min(), tensor.max(), tensor.prod())
        # # 打平后的最小最大值索引
        # print(tensor.argmax(), tensor.argmin())
        # print()
        if (tensor.min() < minr): 
            minr = tensor.min()
        if (tensor.max() >= maxr): 
            maxr = tensor.max()
print(maxr, minr)

1995-RISCY-a-3-c20-u0.9-m1-p6-f1.npy torch.Size([256, 256, 24])
1096-RISCY-a-2-c5-u0.7-m3-p1-f1.npy torch.Size([256, 256, 24])
1548-RISCY-a-3-c2-u0.8-m2-p6-f1.npy torch.Size([256, 256, 24])
1130-RISCY-a-2-c5-u0.8-m1-p3-f1.npy torch.Size([256, 256, 24])
691-RISCY-a-1-c20-u0.8-m3-p7-f1.npy torch.Size([256, 256, 24])
118-RISCY-a-1-c2-u0.85-m4-p7-f0.npy torch.Size([256, 256, 24])
861-RISCY-a-2-c2-u0.7-m3-p6-f1.npy torch.Size([256, 256, 24])
364-RISCY-a-1-c5-u0.85-m4-p5-f0.npy torch.Size([256, 256, 24])
1895-RISCY-a-3-c20-u0.85-m1-p8-f0.npy torch.Size([256, 256, 24])
499-RISCY-a-1-c20-u0.7-m1-p7-f0.npy torch.Size([256, 256, 24])
1745-RISCY-a-3-c5-u0.75-m2-p6-f1.npy torch.Size([256, 256, 24])
9-RISCY-a-1-c2-u0.7-m2-p1-f0.npy torch.Size([256, 256, 24])
912-RISCY-a-2-c2-u0.85-m1-p1-f1.npy torch.Size([256, 256, 24])
332-RISCY-a-1-c5-u0.8-m3-p5-f0.npy torch.Size([256, 256, 24])
1421-RISCY-a-3-c2-u0.75-m3-p5-f0.npy torch.Size([256, 256, 24])
1721-RISCY-a-3-c5-u0.7-m2-p5-f1.npy torch.Size([256, 25

In [3]:
# all tensor sizes are [256, 256, 24]
c = 0
# Loop through all files in the directory
maxr = -99
minr = 99
for filename in os.listdir(save_path2):
    # Check if the file has the expected format
    data = np.load(os.path.join(save_path2, filename))
    tensor = torch.from_numpy(data)
    c+=1
    # if(c==20): break
    print(filename, tensor.shape)

    # # 均值,累加,最小,最大,累积
    print(tensor.mean(), tensor.sum(), tensor.min(), tensor.max(), tensor.prod())
    # # 打平后的最小最大值索引
    # print(tensor.argmax(), tensor.argmin())
    # print()
    if (tensor.min() < minr): minr = tensor.min()
    if (tensor.max() >= maxr): maxr = tensor.max()
print(maxr, minr)

3288-RISCY-b-2-c20-u0.75-m2-p7-f1.npy torch.Size([256, 256, 24])
tensor(0.0086, dtype=torch.float64) tensor(13515.4290, dtype=torch.float64) tensor(0., dtype=torch.float64) tensor(1., dtype=torch.float64) tensor(0., dtype=torch.float64)
9738-zero-riscy-b-2-c5-u0.75-m1-p1-f0.npy torch.Size([256, 256, 24])
tensor(0.0043, dtype=torch.float64) tensor(6690.6278, dtype=torch.float64) tensor(0., dtype=torch.float64) tensor(1., dtype=torch.float64) tensor(0., dtype=torch.float64)
9394-zero-riscy-b-1-c5-u0.75-m1-p2-f0.npy torch.Size([256, 256, 24])
tensor(0.0049, dtype=torch.float64) tensor(7704.8994, dtype=torch.float64) tensor(0., dtype=torch.float64) tensor(1., dtype=torch.float64) tensor(0., dtype=torch.float64)
3794-RISCY-b-3-c20-u0.8-m1-p2-f0.npy torch.Size([256, 256, 24])
tensor(0.0079, dtype=torch.float64) tensor(12486.2137, dtype=torch.float64) tensor(0., dtype=torch.float64) tensor(1., dtype=torch.float64) tensor(0., dtype=torch.float64)
3240-RISCY-b-2-c20-u0.9-m1-p6-f0.npy torch.Size

tensors have shape [256, 256, 24]. Elements have 20-24 number of 1's. 


Values in tensor already lie in range [0,1]

In [5]:
# tensors have shape [256, 256, 24]. 20-24 1's. Values in tensor already lie in range [0,1]
c = 0
# Loop through all files in the directory
maxr = -99
minr = 99
for filename in os.listdir(save_path1):
    # Check if the file has the expected format
    # print(filename, tensor.shape)
    if filename.endswith('.npy'):
        data = np.load(os.path.join(save_path1, filename))
        tensor = torch.from_numpy(data)
        c+=1
        if(c==100): break
        # print(filename, tensor.shape)

        # # 均值,累加,最小,最大,累积
        # print(tensor.mean(), tensor.sum(), tensor.min(), tensor.max(), tensor.prod())
        # # 打平后的最小最大值索引
        # print(tensor.argmax(), tensor.argmin())
        # print()
        print(countlarger(tensor))
        print(count_zeros(tensor))
        print(count_ones(tensor))
        print(print_non_zeros(tensor))
        if (tensor.min() < minr): 
            minr = tensor.min()
        if (tensor.max() >= maxr): 
            maxr = tensor.max()
print(maxr, minr)

0
1231792
20
Non-zero elements in the tensor:
tensor([2.1449e-07, 2.5889e-07, 5.3788e-07,  ..., 3.4864e-04, 3.4864e-04,
        4.3775e-04], dtype=torch.float64)
None
0
1069080
24
Non-zero elements in the tensor:
tensor([1.3950e-09, 1.3096e-09, 2.0746e-08,  ..., 6.9582e-09, 4.7394e-10,
        4.4492e-10], dtype=torch.float64)
None
0
1107461
24
Non-zero elements in the tensor:
tensor([1.1623e-08, 1.5907e-08, 2.9323e-08,  ..., 5.5209e-05, 3.9390e-05,
        4.0496e-05], dtype=torch.float64)
None
0
1116866
24
Non-zero elements in the tensor:
tensor([2.4297e-08, 2.9662e-08, 9.2827e-08,  ..., 1.4959e-03, 1.4959e-03,
        1.4959e-03], dtype=torch.float64)
None
0
1105132
20
Non-zero elements in the tensor:
tensor([3.6659e-03, 2.4476e-04, 1.3350e-03,  ..., 4.7745e-06, 1.0639e-06,
        1.5830e-06], dtype=torch.float64)
None
0
1104301
24
Non-zero elements in the tensor:
tensor([2.6518e-04, 2.5221e-05, 2.5501e-05,  ..., 8.8832e-07, 6.6913e-07,
        6.7205e-07], dtype=torch.float64)
Non

In [4]:
def countlarger(tensor):
    """
    Counts the number of occurrences of the value 1 in a PyTorch tensor.
    
    Args:
        tensor (torch.Tensor): The input tensor.
        
    Returns:
        int: The number of occurrences of the value 1 in the tensor.
    """
    return torch.sum(tensor > 1).item()
def count_ones(tensor):
    """
    Counts the number of occurrences of the value 1 in a PyTorch tensor.
    
    Args:
        tensor (torch.Tensor): The input tensor.
        
    Returns:
        int: The number of occurrences of the value 1 in the tensor.
    """
    return torch.sum(tensor == 1).item()

def count_zeros(tensor):
    """
    Counts the number of occurrences of the value 1 in a PyTorch tensor.
    
    Args:
        tensor (torch.Tensor): The input tensor.
        
    Returns:
        int: The number of occurrences of the value 1 in the tensor.
    """
    return torch.sum(tensor == 0).item()

def print_non_zeros(tensor):
    """
    Prints all the non-zero elements in a PyTorch tensor.

    Args:
        tensor (torch.Tensor): The input tensor.
    """
    non_zeros = tensor[tensor != 0]
    print("Non-zero elements in the tensor:")
    print(non_zeros)